### ISSUE TITLE
새부장소 기능 개발

### ISSUE THREAD

**Issue by jomulagy** [jomulagy/meet_FE#1]
### PROCESS
1. 참여 여부 투표 종료
2. 모임 작성자에게 알림 전송 ( 세부장소를 입력 하세요)
3. 세부장소 입력하고 참여자들에게 알림 전송( 자동/ 버튼입력)

### TODO
- [ ] 장소 API WIKI 작성
- [x] 모임 수정 페이지
- [x] 모임 상세 페이지
- [x] 세부장소 입력 팝업
